<a href="https://colab.research.google.com/github/waleedGeorgy/deep-learning/blob/main/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating basic Constant Tensors

First we'll get familiar with some tensorflow basics

In [ ]:
# Importing TensorFlow
import tensorflow as tf

print(tf.__version__)

2.15.0


In [ ]:
# Creating scalars
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking the num of dimensions in the scalar
scalar.ndim # Got 0 dims

0

In [ ]:
# Creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim # Got 1 dim

1

In [ ]:
# Creating a matrix
matrix = tf.constant([[10,7],
                      [5,9]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  9]], dtype=int32)>

In [ ]:
matrix.ndim # Got 2 dim

2

In [ ]:
# Creating a matrix with a specific data type
matrix = tf.constant([[1.5,2.],
                      [5.,4.6],
                      [9.3,3.]], dtype = tf.float16)
matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1.5, 2. ],
       [5. , 4.6],
       [9.3, 3. ]], dtype=float16)>

In [ ]:
# Creating a tensor
tensor = tf.constant([[[1,2,3],[2,3,4]],
                      [[5,4,3],[2,3,5]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[5, 4, 3],
        [2, 3, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

3

A **Tensor** is a numerical representation of data that acts as the input and output of a deep learning model.

A Tensor is a n-dimensional array. When:
*   n = 0 we get a scalar;
*   n = 1 we get a vector;
*   n = 2 we get a matrix;
* n > 2 we get a tensor.

The number of dimensions in a tensor can be determined by the number of opening and closing square brackets. For example, if a tensor has 3 opening and 3 closing brackets, it means that we are looking at a 3-dimensional tensor.

For scalars and vectors, parentheses are used, where 2 empty parentheses distinguish a scalar, and 2 paranthses with a number (that defines the number of elements in the vector) distinguish a vector.




# Creating basic variable Tensors

Tensors created using .constant() can't have their elements changed. Attempting to change a value here will raise an error.

Tensors that are created using .Variable() can have their elements changed, i.e. we can assign new values to tensor elements.

In [ ]:
# We can't reaasign values in constant tensors
const_tensor = tf.constant([10, 5, 3])
# These 2 lines won't work and will raise errors
const_tensor[0] = 7
const_tensor[0].assign(7)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
# Here we were able to reassign the first value of the variable tensor
var_tensor = tf.Variable([10, 5, 3])
var_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([7, 5, 3], dtype=int32)>

# Creating Random Tensors

In [ ]:
# Creating a random tensor with normal distribution
random_1 = tf.random.Generator.from_seed(42) # Setting an operation specifi random seed
random_1 = random_1.normal(shape=(3,2)) # Creating a random tensor from above seed with shape of 3x2
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Creating a random tensor with uniform distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
tf.random.set_seed(42) # Sets a global random seed
random_4 = tf.random.normal(shape = (3,2))
random_4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519],
       [-2.3880599, -1.0392479]], dtype=float32)>

TensorFlow operates on two levels of random seeds: **global level** seeds and **operation level** seeds.

Due to that, random seeds in Tensorflow follow a certain behaviour, which is explained [here](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

# Shuffling Tensors

Shuffling is needed to get rid of the inherit order that could be present in the tensors, so this order does not affect the learning process of the model.

In [ ]:
not_shuffled = tf.constant([[2,5],
                            [6,10],
                            [1,9]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 6, 10],
       [ 1,  9]], dtype=int32)>

In [ ]:
# .random.shuffle() randomly shuffles the tensor along the first dimension
# Here we're shuffling along the rows
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  9],
       [ 2,  5],
       [ 6, 10]], dtype=int32)>

In [ ]:
# We can set a global seed for the shuffing
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6, 10],
       [ 1,  9],
       [ 2,  5]], dtype=int32)>

# Other ways to create tensors

In [ ]:
# Creating a tensor on ones
ones = tf.ones((3,4))
ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Creating a tensor on zeros
zeros = tf.zeros((3,4))
zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Creating tensors from numpy arrays
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
print(numpy_A)

numpy_tensor = tf.constant(numpy_A)
print(numpy_tensor)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


In [ ]:
# Turning the same numpy array into a tensor of different shape
# Important to note that the length of the np array must be equal to the number of elements in the dimensions
numpy_tensor_new = tf.constant(numpy_A, shape = (2,3,4))
numpy_tensor_new

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
np_array = np.random.rand(3,4)
np_array

array([[0.83105201, 0.04801692, 0.05508163, 0.85325359],
       [0.41820138, 0.27181043, 0.32839905, 0.75375637],
       [0.10986109, 0.95479774, 0.14876413, 0.5736886 ]])

In [ ]:
rand_tensor = tf.constant(np_array, shape = (6,2))
rand_tensor

<tf.Tensor: shape=(6, 2), dtype=float64, numpy=
array([[0.83105201, 0.04801692],
       [0.05508163, 0.85325359],
       [0.41820138, 0.27181043],
       [0.32839905, 0.75375637],
       [0.10986109, 0.95479774],
       [0.14876413, 0.5736886 ]])>

# Getting information from tensors

In [ ]:
# Shape of the tensor
tensor = tf.zeros(shape = (2,3,4,5))
tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# Indexing dimension (indexing on the zeroth axis)
tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# Number of dimensions on the tensor (rank of tensor)
tensor.ndim

4

In [ ]:
# Size of the tensor
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
# Tensor datatype
tensor.dtype

tf.float32

In [ ]:
# Indexing tensors (first 2 elements from each dim)
tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# First element from each dim except for the third dim
tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

# Adding dimensions to tensors

There are two way to add extra dimensions to tensors:
* Using tf.newaxis
* Using tf.expand_dims()

In [ ]:
# Using .newaxis
tensor = tf.constant([[4,5],[1,3]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 3]], dtype=int32)>

In [ ]:
new_tensor = tensor[:, :, tf.newaxis]
new_tensor, new_tensor.ndim

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[4],
         [5]],
 
        [[1],
         [3]]], dtype=int32)>,
 3)

In [ ]:
# Using tf.expand_dims()
tf.expand_dims(tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[4],
        [5]],

       [[1],
        [3]]], dtype=int32)>

# Manipulating Tensors (Tensor Operations)

In [ ]:
# Adding values to tensor elements
tensor = tf.constant([[10,4],[1,3]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [11, 13]], dtype=int32)>

In [ ]:
# Substracting values from tensor elements
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -6],
       [-9, -7]], dtype=int32)>

In [ ]:
# Operations can be done with built-in tf functions
# Manipulating tensors using these functions is faster
tf.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 20],
       [ 5, 15]], dtype=int32)>

In [ ]:
# Squaring the tensor
tensor = tf.range(1,10)
print(tensor)

tf.square(tensor)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Square root of tensor
tf.sqrt(tf.cast(tensor, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Log of tensor
tf.math.log(tf.cast(tensor, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Matrix Multiplication

Matrix multiplication is one of the most important and common operations in deep learning. It is how models learn, update their weights and give outputs etc.

Matrix multiplication is the same as the dot product of two tensor, and is not the element wise product of two tensors.

To Matmul two tensors the inner dimensions need to match.

In [ ]:
print(tensor)

tf.Tensor(
[[10  4]
 [ 1  3]], shape=(2, 2), dtype=int32)


In [ ]:
# Dot product
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[104,  52],
       [ 13,  13]], dtype=int32)>

In [ ]:
# Element-wise product
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  16],
       [  1,   9]], dtype=int32)>

In [ ]:
tens_1 = tf.constant([[1,2,2,4],[3,4,5,10]])
tens_1

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  2,  4],
       [ 3,  4,  5, 10]], dtype=int32)>

In [ ]:
tens_2 = tf.constant([[2,4],[3,7],[1,2],[10,5]])
tens_2

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 3,  7],
       [ 1,  2],
       [10,  5]], dtype=int32)>

In [ ]:
tf.matmul(tens_1, tens_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  42],
       [123, 100]], dtype=int32)>

In [ ]:
tens_3 = tf.constant([[7,5,2,4],[3,8,9,10]])
tens_3

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7,  5,  2,  4],
       [ 3,  8,  9, 10]], dtype=int32)>

In [ ]:
# Inner dims must match
tf.matmul(tens_1, tens_3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 53,  69],
       [134, 171]], dtype=int32)>

In [ ]:
# We can reshape one of the two tensors
tens_3 = tf.reshape(tens_3, shape = (4,2))
tens_3

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 7,  5],
       [ 2,  4],
       [ 3,  8],
       [ 9, 10]], dtype=int32)>

In [ ]:
tf.matmul(tens_1, tens_3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 53,  69],
       [134, 171]], dtype=int32)>

In [ ]:
# We can also transpose the second matrix and perform multiplication
# Transposing is not the same as reshaping
tf.transpose(tens_3)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7,  2,  3,  9],
       [ 5,  4,  8, 10]], dtype=int32)>

In [ ]:
tens_1 = tf.constant([[1,2,2,4],[3,4,5,10]])
tf.matmul(tf.transpose(tens_1), tf.transpose(tens_3))

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 22,  14,  27,  39],
       [ 34,  20,  38,  58],
       [ 39,  24,  46,  68],
       [ 78,  48,  92, 136]], dtype=int32)>

In [ ]:
# Dot product can be performed using .tensordot() (tensor contraction)
# In this case, when performing tensordot along axis 1, we get the normal dot product
tf.tensordot(tens_1, tens_2, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  42],
       [123, 100]], dtype=int32)>

In [ ]:
tens_1

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  2,  4],
       [ 3,  4,  5, 10]], dtype=int32)>

In [ ]:
tens_2

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 3,  7],
       [ 1,  2],
       [10,  5]], dtype=int32)>

In [ ]:
# When performed along the 0 axis, we get dofferent results
# Tensor elements get changed and the dimensions get concatenated
tf.tensordot(tens_1, tens_2, axes = 0)

<tf.Tensor: shape=(2, 4, 4, 2), dtype=int32, numpy=
array([[[[  2,   4],
         [  3,   7],
         [  1,   2],
         [ 10,   5]],

        [[  4,   8],
         [  6,  14],
         [  2,   4],
         [ 20,  10]],

        [[  4,   8],
         [  6,  14],
         [  2,   4],
         [ 20,  10]],

        [[  8,  16],
         [ 12,  28],
         [  4,   8],
         [ 40,  20]]],


       [[[  6,  12],
         [  9,  21],
         [  3,   6],
         [ 30,  15]],

        [[  8,  16],
         [ 12,  28],
         [  4,   8],
         [ 40,  20]],

        [[ 10,  20],
         [ 15,  35],
         [  5,  10],
         [ 50,  25]],

        [[ 20,  40],
         [ 30,  70],
         [ 10,  20],
         [100,  50]]]], dtype=int32)>

# Changing Tensors' Data Type

In TensorFlow, tensors can have different precisions (e.g. float32 tensor vs. float16 tensor). This **mixed precision** can affect the performance and accuracy of the models.

**Mixed precision** is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory. By keeping certain parts of the model in the 32-bit types for numeric stability, the model will have a lower step time and train equally as well in terms of the evaluation metrics such as accuracy.

More info [here](https://www.tensorflow.org/guide/mixed_precision).

In [ ]:
# The default precision is 32
A = tf.constant([[1.6, 5.2],[1.1, 6.0]])
A.dtype

tf.float32

In [ ]:
B = tf.constant([[5, 4],[7, 9]])
B.dtype

tf.int32

In [ ]:
# Precision can reduced using .cast()
C = tf.cast(B, dtype = tf.float16)
C.dtype

tf.float16

In [ ]:
# Data type can also be changed
D = tf.cast(B, dtype = tf.float16)
D.dtype

tf.float16

# Tensor Aggregation (Reduction)

Aggregating tensors means condensing them from their original values to a smaller amount of values. For example: minimum of tensor, maximum, mean, absolute, sum, etc...

In [ ]:
# Absolute of tensor
A = tf.constant([[-5,1],[-2,-7]])
tf.abs(A)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 1],
       [2, 7]], dtype=int32)>

In [ ]:
# For other operations we will create a new bigger tensor
ten = tf.constant(np.random.randint(1, 100, size = 50))
ten

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([89, 25, 64, 16, 47,  9, 79,  7, 13, 89, 25, 49, 71,  4, 41,  3, 42,
       65, 88,  6, 84, 29, 71, 61,  4, 51, 52, 43, 48,  6, 71,  9, 72, 17,
       18, 72, 34, 29, 66,  5, 38, 88, 23, 26,  3, 27,  4, 62, 24, 91])>

In [ ]:
# Minimum of tensor
tf.reduce_min(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
# Maximum of tensor
tf.reduce_max(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=91>

In [ ]:
# Mean of tensor
tf.reduce_mean(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=41>

In [ ]:
# Sum of tensor
tf.reduce_sum(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=2060>

In [ ]:
# Variance of tensor
# For variance (and standard deviation) the tensor must be real or complex type, so we change its type to float32
tf.math.reduce_variance(tf.cast(ten, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=814.7199>

In [ ]:
# Variance of tensor
tf.math.reduce_std(tf.cast(ten, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.543299>

In [ ]:
# Variance and STD can be computed using tensorflow_probability module
import tensorflow_probability as tfp
print(tfp.stats.variance(ten))
print(tfp.stats.stddev(tf.cast(ten, dtype = tf.float32)))

tf.Tensor(814, shape=(), dtype=int64)
tf.Tensor(28.543299, shape=(), dtype=float32)


# Max and min Index of a Tensor

In [ ]:
tf.random.set_seed(42)
A = tf.random.uniform(shape = [50])
A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Positional maximum
# The max value is at index 42
tf.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Indexing the tensor on the max index gives us its value
A[tf.argmax(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Positional minimum
# The min value is at index 16
tf.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Indexing the tensor on the min index gives us its value
A[tf.argmin(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing a Tensor

Squeezing a tensor means removing all size 1 dimensions from said tensor. This, alongside .expand_dims(), allow us to manipulate the number of dimensions in a tensor, which is prevelant in deep learning models

In [ ]:
tf.random.set_seed(42)
G = tf.random.uniform(shape = (1,5,1,6,1))
G

<tf.Tensor: shape=(1, 5, 1, 6, 1), dtype=float32, numpy=
array([[[[[0.6645621 ],
          [0.44100678],
          [0.3528825 ],
          [0.46448255],
          [0.03366041],
          [0.68467236]]],


        [[[0.74011743],
          [0.8724445 ],
          [0.22632635],
          [0.22319686],
          [0.3103881 ],
          [0.7223358 ]]],


        [[[0.13318717],
          [0.5480639 ],
          [0.5746088 ],
          [0.8996835 ],
          [0.00946367],
          [0.5212307 ]]],


        [[[0.6345445 ],
          [0.1993283 ],
          [0.72942245],
          [0.54583454],
          [0.10756552],
          [0.6767061 ]]],


        [[[0.6602763 ],
          [0.33695042],
          [0.60141766],
          [0.21062577],
          [0.8527372 ],
          [0.44062173]]]]], dtype=float32)>

In [ ]:
# Squeezing the tensor
# This will turn the tensor from 1x5x1x6x1 to 5x6
tf.squeeze(G)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236],
       [0.74011743, 0.8724445 , 0.22632635, 0.22319686, 0.3103881 ,
        0.7223358 ],
       [0.13318717, 0.5480639 , 0.5746088 , 0.8996835 , 0.00946367,
        0.5212307 ],
       [0.6345445 , 0.1993283 , 0.72942245, 0.54583454, 0.10756552,
        0.6767061 ],
       [0.6602763 , 0.33695042, 0.60141766, 0.21062577, 0.8527372 ,
        0.44062173]], dtype=float32)>

# One-hot Encoding Tensors

**One-hot encoding** is a technique in machine learning that turns categorical data, like colors (red, green, blue), into numerical data. It creates new binary columns for each category, with a 1 marking the presence of that category and 0s elsewhere.

One-hot encoding is one of the main concepts in machine learning, and is one of the most basic methods of turning categorical text data into numerical representations that computers can work with.

Today, one-hot enconding is less used, and other methods, like text vectorization are better.

In [ ]:
colors = [0,1,2,3] # For example for colors
tf.one_hot(colors, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

#Tensors & NumPy

TensorFlow and NumPy are two very compatible libraries, and we can easily and seemlessly covert from one type to the other.

One must be aware that when converting from tensors to np arrays or vice versa, the data type can change.

The main difference between the two, is that tensors can harness the power of **GPUs** and **TPUs**.

**Tensor Processing Unit (TPU)** is an AI accelerator application-specific integrated circuit (ASIC) developed by Google for neural network machine learning, using Google's own TensorFlow software. More info [here](https://cloud.google.com/tpu).

In [ ]:
# Creating a tensor from a numpy array
import numpy as np

tensor = tf.constant(np.arange(1.,6.))
tensor

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 4., 5.])>

In [ ]:
# Turning the tensor back into a numpy array
n_arr = np.array(tensor)
n_arr, n_arr.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

#Extra: Checking for GPU / TPU

In [ ]:
# Checking the list devices currently available in the runtime
# Here we can see that a CPU is available
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
# After switching to a GPU, we can see it listed below
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

The good thing is that TensorFlow doesn't need any additional configuration to run on a GPU. If a CUDA-enabled device is available, TensorFlow will use it automatically.

**CUDA (Compute Unified Device Architecture)** is a parallel computing platform and programming model developed by NVIDIA. It enables developers to harness the power of NVIDIA GPUs to accelerate their applications. CUDA provides a set of programming tools and libraries that allow developers to write high-performance applications that can leverage the parallel processing capabilities of GPUs.